### ISSUE TITLE
[BUG] - restrictDismissal not working

### ISSUE THREAD

**Issue by khuffie** [jevonmao/PermissionsSwiftUI#44]
Hello,

My app got rejected because the X button in the modal doesn't work. Looking at 1.3.0, I see restrictDismissal is a setting that's available.

Unfortunately, it doesn't seem to work.

Here's my code:

```
                .JMModal(
                    showModal: $appState.showPermissionsDialogue,
                    
                    for: [.locationAlways, .calendar, .reminders, .health(categories: .init(read: HealthKitHelper.shared.permissionGroups.allTypes, write: HealthKitHelper.shared.permissionGroups.toWrite) )],
                    autoDismiss: true,
                    autoCheckAuthorization: true,
                    restrictDismissal: false,
                    onAppear: {},
                    onDisappear: {
                        EventsHelper.shared.getAuthorizationStatus()
                        
                    }
                )
```

**Comment by jevonmao** [comment]
@khuffie Thank you for the bug report. I tried to replicate your code on my side as best as I can:
```
.JMModal(
                            showModal: $showModal,
                            
                            for: [.locationAlways, .calendar, .reminders],
                            autoDismiss: true,
                            autoCheckAuthorization: true,
                            restrictDismissal: false,
                            onAppear: {},
                            onDisappear: {
                                
                                
                            }
                        )
```
Please see the screen recording.

https://user-images.githubusercontent.com/64660730/110180717-28b35900-7dbf-11eb-980a-7d0ec57659a7.mp4

I cannot seem to reproduce the bug you mentioned. Since you disabled `restrictDismissal`, that means the user can exit the modal view by swiping or tapping the x-button without interacting all permissions. If `restrictDismissal` is `true`, the user won't be able to dismiss until they interacted with all the permissions.

**Comment by khuffie** [comment]
I figured out the issue.

I had the .JMModal modifier on the root App class. I moved it to the
ContentView class and it started working.
