### ISSUE TITLE
[BUG] - Apple rejects review because of HealthKit

### ISSUE THREAD

**Issue by mrsunx** [jevonmao/PermissionsSwiftUI#84]
**Describe the bug**
In version 1.5.0, I only selected Notification and did a TestFlight review. But it was rejected by Apple and HealthKit was detected.

```
Guideline 2.5.1 - Performance - Software Requirements
We noticed that your app uses HealthKit, but your app does not appear to include any primary features that require health or fitness data.
```

**Comment by jevonmao** [comment]
@mrsunx I think I know what the issue is. The shared code module, `CorePermissionsSwiftUI` contains certain code that involves `import HealthKit` in order for structs like `HKAccess` and some mock testing objects to function. 

I will move those code files into the health module and release a new version soon. Thanks for the report and support!

**Comment by jevonmao** [comment]
@mrsunx Try 1.5.1 and let me know if it's fixed.

**Comment by mrsunx** [comment]
> @mrsunx Try 1.5.1 and let me know if it's fixed.

It’s worked, thanks a lot
